### PR TITLE
Add an optional pop-up notification when auto-turn is toggled

### LINKED ISSUE #499: Add Tracker Held In hand common issue.
While it's not strictly our fault, it is a recurring issue encountered wehre binds don't work because trackers are in the controrller roles. Add this to common issues section and fix.

### LINKED ISSUE #502: update documentation can't modify custom keybinds while running
Need to update documentation maybe common issues that keybinds cannot be edited while program is running.

### PR DESCRIPTION
**Pull request by feilen**
These changes are mostly a copy of PTT's pop-up with one small change: whichever icon indicator is used pops up for both states, and for only one second. 

Finished:
- pop up
- icons (need feedback? do they look okay? They seem alright when using)
- boolean setting (double check my work)

Needed:
- ~~GUI checkbox~~

Would be nice:
- Is there any way set overlay transparency? It'd look a little nicer to have the icon pop in instantly for one second, then fade for one second.

ykeara edit:

fixes #499
fixes #502

Fixes some documentation format errors, adds some clarifications and new issues (to documentation)
Fixes some formating to properly show deg symbol in rotation tab.

### CODE REVIEW

**Comment by ykeara** [comment]
you can set overlay transparency but It's an api call every time. there is no "fade out over time" `SetOverlayAlpha` is function.

**Comment by feilen** [comment]
> you can set overlay transparency but It's an api call every time. there is no "fade out over time" `SetOverlayAlpha` is function.

It'd be quite easy to implement that the way I have it now (we check every tick if we need to dismiss the notification) but would that be expensive?

**Comment by ykeara** [comment]
hard to say we have gotten caught out before from single frame calls, but at the same time we def have calls that run per frame.... without trying/profiling specific calls hard to say.

**Comment by feilen** [comment]
A thought: maybe we don't even need to make this optional? It's fairly something you'd want, and only going to be showing up a lot if you go in to bind auto-turn toggle to a key. That'd also save the step of having to implement the GUI changes.

**Comment by feilen** [comment]
Yeah that's what I was figuring, if we ended up not adding GUI toggleability, just default it to 'on' and if anyone wants otherwise they can go manually edit their save.

I'll add the other stuff when I get a chance.

**Comment by ykeara** [comment]
Up to you I have the macro in my changes locally if you want them, but if you don't want the UI at all we don't need the macro (really only thing that needs to be changed would be the default value to true vs false)

**Pull request merged**
