### PR TITLE
Settings objects

### PR DESCRIPTION
**Pull request by username223**
## Problem

The current method of saving logically connected variables is to use the QSettings API directly.
This leads to large amounts of code duplication since every controller has to have their own implementation.

It also leads to slow development since new features will usually have to implement their own settings system.

## Considerations

The API should be resistant to internal changes.

The API should be simple to use.

## Requirements

The API MUST allow the permanent storage of objects. Internal changes to objects MUST NOT be a breaking change.

## Public API

The public API is in the `settings_object.h` file in the `settings` namespace.

The API consists of two parts, an imperative set of functions and a virtual class that objects must implement.

The imperative functions are straightforward.
```cpp
void saveObject( const ISettingsObject& obj );

void loadObject( ISettingsObject& obj );

void saveNumberedObject( const ISettingsObject& obj, const int slot );

void loadNumberedObject( ISettingsObject& obj, const int slot );

int getAmountOfSavedObjects( ISettingsObject& obj );
```
The `numberedObject` versions can be used for saving an arbitrary amount of objects, retrievable with the same `slot`.

`getAmountOfSavedObjects` will return the amount of objects, starting from _1_, that exist contiguously.
Will return `0` if no objects have been saved as `saveNumberedObject(obj, 1)`.

The `ISettingsObject`s will have to be implemented by the object to be saved.
```cpp
class ISettingsObject
{
    public:
        virtual ~ISettingsObject() {}

        virtual SettingsObjectData saveSettings() const = 0;

        virtual void loadSettings( SettingsObjectData& obj ) = 0;

        virtual std::string settingsName() const = 0;
};
```

The `settingsName()` is used internally for correctly identifying objects and it should be globally unique.

The `ISettingsObject` communicates with the API through a `SettingsObjectData` object, which contains the variables of the object in a First-In First-Out (FIFO) format.

The contents of the object can be set or retrieved through three templated functions.
```cpp
class SettingsObjectData
{
    public:
        template <typename Value> void addValue( const Value value );

        template <typename Value>
            Value getNextValueOrDefault( const Value defaultValue );

        template <typename Value> bool hasValuesOfType();
}
```
The different types are stored differently, so `addValue<int>()`, `addValue<double>()`, `getNextValueOrDefault<double>()` would return the value added second, but the first double value.

An example implementation for a struct can be found below.
```cpp
struct A : settings::ISettingsObject
{
    bool val1 = true;
    int val2 = 1123;
    double val3 = 1.0003;
    double val4 = 1.0004;
    double val5 = 1.0005;
    std::string val6 = "val6";

    std::string settingsName() const override
    {
        return "SettingsTestStruct";
    }

    void loadSettings( settings::SettingsObjectData& obj ) override
    {
        val1 = obj.getNextValueOrDefault( false );
        val2 = obj.getNextValueOrDefault( 1 );
        val3 = obj.getNextValueOrDefault( 3.0 );
        val4 = obj.getNextValueOrDefault( 4.0 );
        val5 = obj.getNextValueOrDefault( 5.0 );
        val6 = obj.getNextValueOrDefault<std::string>( "default" );
    }

    settings::SettingsObjectData saveSettings() const override
    {
        settings::SettingsObjectData o;
        o.addValue( val1 );
        o.addValue( val2 );
        o.addValue( val3 );
        o.addValue( val4 );
        o.addValue( val5 );
        o.addValue( val6 );

        return o;
    }
};
```
Values of different types can be returned in any order, although it is recommended to save and load settings in the same order.

## Other Solutions

Simply copying the contents of an object (think direct `memcpy()`) was considered but was not chosen because every addition or removal of a struct member would be a breaking change. 
Additionally, the C++ compiler is free to insert padding in the struct, meaning different compilations could interpret data differently.

----

Above is the spec found in `docs/Settings-Object-API.md`.

Additional notes:

* Changing systems over to this new API will be a breaking change since the numbered objects are saved as `[StructName-99]` where 99 is the int passed to the function. Since every tab controller has their own implementation it would not be possible to implement this in a backwards compatible way.

* The API currently only supports `int/double/bool/std::string` values. This can easily be extended.

* Let me know if you have any ideas for changes.

### CODE REVIEW

**Comment by ykeara** [comment]
In regards to `saveNumberedObject` and `loadNumberedObject` personally I think it needs to be clarified in code or documentation to explain what `slot` is. as it could be confusing imo to another developer on-boarding onto the project. (its not immediately obvious that its a essentially a list)


In regards to FIFO While it would minimize memory footprint, It means ANY-time we get or set a variable we have to touch all variables and its always a o(n) operation.

So I suppose is the intent to use `m_` variables for local changes during program execution and just on init, and exit save to the object? or are we trying to use the object as are variables i.e. if we adjust it we change it? I am more for the former, as our memory footprint is small enough, but every cpu clock matters.

so ultimately I think the FIFO could work fine w/ a few caveats. I think we need to encourage all tab controllers then to have a `onexit()` function or similiar to save settings, and on `initstage1()` we just read from the objects.

I also think that instead of individual `getNextValueOrDefault()` we should only have a `getobjects()` and perhaps accordingly a `getobjectlength()` or similiar. I am concerned by having no checks that we are going to have issues adding new settings values, as people could easily forget to add it in appropriate code. i.e. it is mostly just on the developer side as a safety measure imo.

**Comment by ykeara** [comment]
Also concern should be noted if we need to delete a variable or reset one, in order to force this change we would have an ever expanding settings file. (though this also exists in current implementation)

**Comment by username223** [comment]
> In regards to `saveNumberedObject` and `loadNumberedObject` personally I think it needs to be clarified in code or documentation to explain what `slot` is. as it could be confusing imo to another developer on-boarding onto the project. (its not immediately obvious that its a essentially a list)

Agreed. I wanted to write some docstrings for the functions at some point, but I wanted to get your opinions on the API itself before I started writing.

> or are we trying to use the object as are variables i.e. if we adjust it we change it?

The intention was that the owner of the object handles when to save/load the object. I wanted to do something like the normal settings API but couldn't really come up with a solution that wasn't either cumbersome to use, slow as hell or a massive pain to implement new objects for.

> so ultimately I think the FIFO could work fine w/ a few caveats. I think we need to encourage all tab controllers then to have a onexit() function or similiar to save settings, and on initstage1() we just read from the objects.

It seems like most of the places where structs are used for settings there's a `loadSettings()` or something function, but I really like the idea of having explicit exit functions for every controller.

> I also think that instead of individual getNextValueOrDefault() we should only have a getobjects() and perhaps accordingly a getobjectlength() or similiar. I am concerned by having no checks that we are going to have issues adding new settings values, as people could easily forget to add it in appropriate code. i.e. it is mostly just on the developer side as a safety measure imo.

I considered just returning a `std::vector` of the saved values, but ran into some issues when it became apparent that the object doesn't really know which values belong to which variables.

It also (IMO) complicates loading the object when no settings file is present, since there would essentially have to be an if statement for an empty vector, that fills out a complete struct, one if only one value was added, etc.

What I envisioned was this:
```cpp
struct A : settings::ISettingsObject
{
    bool val1 = false;

    void loadSettings( settings::SettingsObjectData& obj ) override
    {
        val1 = obj.getNextValueOrDefault( false );
    }

    settings::SettingsObjectData saveSettings() const override
    {
        settings::SettingsObjectData o;

        o.addValue( val1 );

        return o;
    }
};
```
A basic struct containing one member. If no settings file is found `val1` defaults to the provided value.
Adding another variable just means adding 2 lines more.
```cpp
struct A : settings::ISettingsObject
{
    bool val1 = false;
	bool val2 = true;

    void loadSettings( settings::SettingsObjectData& obj ) override
    {
        val1 = obj.getNextValueOrDefault( false );
        val2 = obj.getNextValueOrDefault( true);
    }

    settings::SettingsObjectData saveSettings() const override
    {
        settings::SettingsObjectData o;

        o.addValue( val1 );
		o.addValue( val2 );

        return o;
    }
};
```
If an old settings file is found `val1` will use that value, while `val2` will use the default value.
This is IMO very clear and saves logic in the individual implementations.
A `std::vector` implementation with the same functionality would have to look something like
```cpp
struct A : settings::ISettingsObject
{
    bool val1 = false;
	bool val2 = true;

    void loadSettings( settings::SettingsObjectData& obj ) override
    {
        const auto v = obj.getVector<bool>();
		if (v.empty()) {
			// Vars are initialized in definitions so no need to set them
			return;
		}

		if (v.size() == 1) {
			val1 = v.at(0);
			// val2 is initialized in the definition
			return;
		}

		val1 = v.at(0);
		val2 = v.at(1);
    }

    settings::SettingsObjectData saveSettings() const override
    {
        settings::SettingsObjectData o;

        o.addValue( val1 );
		o.addValue( val2 );

        return o;
    }
};
```
And further variables would only make the function grow even larger in size and complexity, especially if other types are also included.

> Also concern should be noted if we need to delete a variable or reset one, in order to force this change we would have an ever expanding settings file. (though this also exists in current implementation)

I agree, although I don't think there's any really good way of dealing with backwards compatibility. We would either always have to account for the fact that some people might have an old settings file, or we need to actively wipe the settings file every major update, which I also don't think is ideal since usually a lot of settings are still backwards compatible.

A suggestion could be something like this, if we wanted to deprecate `val1`.
```cpp
struct A : settings::ISettingsObject
{
	bool val2 = true;

    void loadSettings( settings::SettingsObjectData& obj ) override
    {
        obj.eatDeprecatedValue<bool>();
        val2 = obj.getNextValueOrDefault( true);
    }

    settings::SettingsObjectData saveSettings() const override
    {
        settings::SettingsObjectData o;

        o.addDeprecatedValue<bool>();
		o.addValue( val2 );

        return o;
    }
};
```

**Comment by username223** [comment]
And I actually made a mistake in the vector example.

```cpp
if (v.size() == 1) {
	val1 = v.at(0); // should be val2 = v.at(1) instead
	// val2 is initialized in the definition
	return;
}
```

**Comment by ykeara** [comment]
I think you addressed my concerns TBH, deprecated values are still the only thing that I really don't like, but not a phenomenal way of dealing w/ it.... Though I suppose we could change the settings file name to force a change on breaking change etc.

But essentially.

settings would only save/load (to disk) at close (and init)  (or I suppose we could put a "save-settings" button somewhere)

**Pull request merged**
