### PR TITLE
Refactor actions into separate action sets

### LINKED ISSUE #111: Move SteamVR actions into separate action sets
This provides improved cohesion because actions are grouped with other, relevant actions instead of just being listed A-Z in one big pile.

### PR DESCRIPTION
**Pull request by username223**
## This PR:
* Moves actions into named action sets relevant to them.
* Fixes a few whitespace issues.
* Fixes #111.

## Noteworthy Items:
* The haptics bindings have their own Haptics category. This was considered the cleanest solution compared to having a "main" action set for random actions.
* The categories have been added as per #109.

### CODE REVIEW

**Comment by ykeara** [comment]
Okay I fixed the issue, there was a "/" instead of a "\" in paths.cpp binarydirectoryfindfile()

I pushed an update, that seems to fix for windows, But unsure if we need compiler directive for linux.

**Comment by Kung-vr** [comment]
Height offset and snap turn configuration options are in the "Motion" tab in the ui so it might make sense to group them with the other motion actions. They're useful for more than just accessibility concerns. If you feel the motion action set is become to large though I'm ok with them splitting off too.

**Comment by ykeara** [comment]
Action set's seemed to work simultaneously. fine though.

**Comment by ykeara** [comment]
I should not there are also some conflict's with the default hmd bindings I have in file, but they will probably just be flat out removed (and attempted to be worked back in in future)

**Comment by ykeara** [comment]
Seems to work good now!

**Pull request merged**
