### PR TITLE
Change url for bindings to correctly work

### PR DESCRIPTION
**Pull request by robert-j-webb**
I found the URL needs a query parameter to work.

### CODE REVIEW

**Comment by robert-j-webb** [comment]
image


And without the query param: 

image

**Comment by ykeara** [comment]
I'll need to look at this again,  Previously it worked in some browsers and not others.... because of some security feature. Not sure what the `proper` solution really is.

**Comment by robert-j-webb** [comment]
Yeah I'm not sure what the *best* answer is, I just wanted to contribute in a way that might unfrustrate someone.

**Comment by ykeara** [comment]
I don't think this is the Right Solution

Just Tried Both Ways in Chrome/Firefox and Edge.

Worked Fine Both Ways In Firefox, but again Failed Both Ways for Edge and Chrome, def worth looking into though.

**Comment by ykeara** [comment]
Going to Close this PR out, and make an issue of it. This solution doesn't appear to be the "correct" way, but it is worth updating.

**Pull request closed without merging**
